module.exports = [
    'બાબરકોટ', 'Babarkot',
    'ભાડલા', 'Bhadla',
    'ભદ્રાવડી', 'Bhadravadi',
    'ભાંભણ', 'Bhambhan',
    'બોડી', 'Bodi',
    'ચકમપર', 'Chakampar',
    'ઢાંકણીયા', 'Dhankaniya',
    'ઢીંકવાળી', 'Dhinkwali',
    'ગધડીયા', 'Gadhadiya',
    'હડાદડ', 'Hadadad',
    'જોટીંગડા', 'Jotingda',
    'કાણીયાદ', 'Kaniyad',
    'કરીયાણી', 'Kariyani',
    'કેરીયા નં 1', 'Keriya No. 1',
    'કેરીયા નં 2', 'Keriya No. 2',
    'ખાખોઇ', 'Khakhoi',
    'કુંભારા', 'Kumbhara',
    'લાઠી', 'Lathi',
    'લીંબોડા', 'Limboda',
    'મોટા છેડા', 'Mota Cheda',
    'મોતી વિરવા', 'Moti Virva',
    'નાગલપર', 'Nagalpar',
    'નાના છેડા', 'Nana Cheda',
    'નાના પાળીયાદ', 'Nana Paliyad',
    'નાની વિરવા', 'Nani Virva',
    'પાળીયાદ', 'Paliyad',
    'પાટી', 'Pati',
    'પીપળીયા', 'Pipliya',
    'પીપરડી', 'Pipardi',
    'રાજપરા', 'Rajpara',
    'રંગપર', 'Rangpar',
    'રતનપર', 'Ratanpar',
    'રતનવાવ', 'Ratanvav',
    'રોહીશાળા', 'Rohishala',
    'સજેલી', 'Sajeli',
    'સલાઈયા', 'Salaiya',
    'સમઢીયાળા નં 1', 'Samadhiyala No. 1',
    'સમઢીયાળા નં 2', 'Samadhiyala No. 2',
    'સાંગાવદર', 'Sangavdar',
    'સાંકરડી', 'Sankardi',
    'સરવા', 'Sarva',
    'સરવઈ', 'Sarvai',
    'શેરથલી', 'Sherthali',
    'શિરવાણીયા', 'Shirvaniya',
    'તાજપર', 'Tajpar',
    'તરઘરા', 'Targhara',
    'તુરખા', 'Turkha',
    'વાજેલી', 'Vajeli',
    'ઝમરાળા', 'Zamarala',
    'ઝરીયા', 'Zariya',
    'ઝીંઝાવદર', 'Zinzavadar'

];